# Generated by Django 3.1.1 on 2020-09-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcuser',
            name='useremail',
            field=models.EmailField(blank=True, max_length=128, verbose_name='사용자이메일'),
        ),
    ]
